name: CI staging

on:
  push:
    branch:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: yarn version
        run: yarn -v

      - name: Get npm cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: yarn install
        run: yarn install

      - name: yarn generate
        run: yarn run generate
      
      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: npm install in functions dir
        run: cd functions; npm install; cd ..

      - name: create empty dist dir
        run: mkdir dist

      - name: Deploy to Firebase
        run: firebase deploy --token $FIREBASE_TOKEN --project=staging --only hosting,functions:app
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
